In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
lr=pd.read_csv('/content/drive/MyDrive/Python Datasets/Social_Network_Ads(1).csv')

In [3]:
lr.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
lr.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [5]:
lr.describe()

User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [6]:
X=lr.iloc[:,[1,2,3]].values
y=lr.iloc[:,4].values

In [7]:
print(X)

[['Male' 19 19000]
 ['Male' 35 20000]
 ['Female' 26 43000]
 ...
 ['Female' 50 20000]
 ['Male' 36 33000]
 ['Female' 49 36000]]


In [8]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,0]=le.fit_transform(X[:,0])

In [9]:
print(X)

[[1 19 19000]
 [1 35 20000]
 [0 26 43000]
 ...
 [0 50 20000]
 [1 36 33000]
 [0 49 36000]]


In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [11]:
print(X_train)

[[1 29 75000]
 [0 38 80000]
 [1 45 26000]
 [0 54 108000]
 [1 46 23000]
 [0 23 28000]
 [1 37 75000]
 [1 42 65000]
 [0 35 71000]
 [0 51 146000]
 [1 39 96000]
 [0 24 89000]
 [0 58 95000]
 [1 25 22000]
 [1 41 59000]
 [1 28 89000]
 [0 42 80000]
 [0 42 108000]
 [0 46 96000]
 [0 47 113000]
 [0 33 28000]
 [1 19 25000]
 [1 49 89000]
 [0 31 15000]
 [0 30 79000]
 [1 48 141000]
 [0 32 117000]
 [0 37 71000]
 [0 18 86000]
 [0 42 79000]
 [0 27 84000]
 [1 40 65000]
 [1 57 74000]
 [0 26 15000]
 [0 26 80000]
 [1 29 43000]
 [0 33 149000]
 [1 39 42000]
 [0 54 104000]
 [1 36 33000]
 [0 46 32000]
 [0 40 142000]
 [0 37 62000]
 [1 29 148000]
 [0 37 57000]
 [1 35 50000]
 [0 42 53000]
 [1 35 38000]
 [0 41 30000]
 [0 40 72000]
 [1 26 15000]
 [0 31 68000]
 [1 35 53000]
 [0 35 25000]
 [1 30 89000]
 [1 41 72000]
 [1 28 123000]
 [0 46 82000]
 [0 22 63000]
 [0 45 22000]
 [1 30 49000]
 [0 34 25000]
 [0 40 75000]
 [0 32 117000]
 [0 23 82000]
 [1 26 80000]
 [0 48 131000]
 [1 59 143000]
 [1 35 55000]
 [1 34 43000]
 [0 39

# Feature Scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [13]:
print(X_train)

[[ 1.02166316 -0.84252154  0.1301563 ]
 [-0.97879618  0.04175763  0.2777019 ]
 [ 1.02166316  0.72953032 -1.31579061]
 [-0.97879618  1.61380949  1.10395728]
 [ 1.02166316  0.82778356 -1.40431797]
 [-0.97879618 -1.43204099 -1.25677236]
 [ 1.02166316 -0.05649561  0.1301563 ]
 [ 1.02166316  0.43477059 -0.16493491]
 [-0.97879618 -0.2530021   0.01211982]
 [-0.97879618  1.31904976  2.22530386]
 [ 1.02166316  0.14001087  0.74984783]
 [-0.97879618 -1.33378775  0.54328399]
 [-0.97879618  2.00682245  0.72033871]
 [ 1.02166316 -1.23553451 -1.43382709]
 [ 1.02166316  0.33651735 -0.34198963]
 [ 1.02166316 -0.94077478  0.54328399]
 [-0.97879618  0.43477059  0.2777019 ]
 [-0.97879618  0.43477059  1.10395728]
 [-0.97879618  0.82778356  0.74984783]
 [-0.97879618  0.9260368   1.25150288]
 [-0.97879618 -0.44950858 -1.25677236]
 [ 1.02166316 -1.82505395 -1.34529973]
 [ 1.02166316  1.12254328  0.54328399]
 [-0.97879618 -0.64601506 -1.64039093]
 [-0.97879618 -0.7442683   0.24819278]
 [ 1.02166316  1.02429004

In [17]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()
classifier.fit(X_train,y_train)

LogisticRegression()

In [18]:
y_pred=classifier.predict(X_test)
y_pred

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0])

In [16]:
# Create Confusion Matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[71,  2],
       [15, 32]])

In [19]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

In [20]:
print('Accuracy Score: ',accuracy_score(y_test,y_pred))
print('Precision Score: ',precision_score(y_test,y_pred))
print('Recall Score: ',recall_score(y_test,y_pred))
print('F1 Score: ',f1_score(y_test,y_pred))

Accuracy Score:  0.8583333333333333
Precision Score:  0.9411764705882353
Recall Score:  0.6808510638297872
F1 Score:  0.7901234567901235


# Implement Gaussian NB

In [21]:
from sklearn.naive_bayes import GaussianNB
classifier_NB=GaussianNB()
classifier_NB.fit(X_train,y_train)

GaussianNB()

In [22]:
y_predNB=classifier_NB.predict(X_test)
y_predNB

array([1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0])

In [23]:
cmNB=confusion_matrix(y_test,y_predNB)
cmNB

array([[71,  2],
       [ 9, 38]])

In [24]:
print('Accuracy Score  NB: ',accuracy_score(y_test,y_predNB))
print('Precision Score NB: ',precision_score(y_test,y_predNB))
print('Recall Score NB: ',recall_score(y_test,y_predNB))
print('F1 Score NB: ',f1_score(y_test,y_predNB))

Accuracy Score  NB:  0.9083333333333333
Precision Score NB:  0.95
Recall Score NB:  0.8085106382978723
F1 Score NB:  0.8735632183908046


In [28]:
age=45
gender=0
Estimated_Salary=35000
deepak=0
output=classifier.predict(sc.transform([[gender,age,Estimated_Salary]]))
if output==1:
  print('Purchased')
else:
  print('Not Purchased')

Not Purchased
